### ISSUE TITLE
This docker container is amazing, any chance you could also create one for Arena ?

### ISSUE THREAD

**Issue by mitermayer** [pauleve/docker-mtgo#51]
Hi @pauleve ,

Been enjoying using this docker container! I was wondering if you plan on having one for MTGA as well ? should be quite similar to this one I imagine! 

It seems to be working well by default on wine with "PlayOnLinux" but would much rather play it within a docker container itself as it plays better with my current setup (I use I3 vm as the desktop manager, running apps dierectly with wine tends to break cursor interactions when moving to other tile)

**Comment by pauleve** [comment]
Thanks for this encouraging feedback :-)

Unfortunately, I'm not planning building any Docker for Arena, essentially because I'm not playing standard ;-)
It should be rather similar indeed, although hardware acceleration must probably be included for OpenGL/DirectX which can be tricky ; but projects like https://github.com/mviereck/x11docker should make this possible, if not straightforward, for linux (but I assume they will make official releases of Arena for macOS).

For your issue with PlayOnLinux, have you tried with "emulate a desktop" setting of winecfg?

**Comment by pauleve** [comment]
If you don't have an Nvidia card, you might want to give a try to https://github.com/pauleve/docker-mtgo/blob/master/mtga/run-mtga (same usage as run-mtgo script)

**Comment by apetresc** [comment]
For what it's worth, the Lutris script for MTGA works perfectly for most people.

**Comment by apetresc** [comment]
@mitermayer It's for Lutris: https://lutris.net/about/
